version: "3.8"

services:

  cassandra-1:
    image: cassandra:phd-cass-3-11-9
    container_name: cassandra-1
    ports:
      - 9042:9042 # cqlsh
      - 7199:7199 # jmx
      - 7000:7000 # internode communication
      - 7001:7001 # tls internode
      - 7071:7070 # jmx
#      - 9103:9103 # jmx

    volumes:
      - "./data/cassandra-1:/var/lib/cassandra"
    environment: 
      - "CASSANDRA_SEEDS=cassandra-1"
      - "CASSANDRA_CLUSTER_NAME=phd-cass"
      - "CASSANDRA_DC=se1"
      - "CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch"
    restart: unless-stopped
    networks: 
      - backend
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2.3G
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "describe keyspaces" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 15s
    build:
      context: ./configs/cass

  cassandra-2:
    image: cassandra:phd-cass-3-11-9
    container_name: cassandra-2
    ports:
      - 9142:9042 # cqlsh
      - 7299:7199 # jmx
      - 7100:7000 # internode communication
      - 7101:7001 # tls internode
      - 7072:7070 # jmx
#      - 9203:9103 # jmx
    volumes:
      - "./data/cassandra-2:/var/lib/cassandra"
    environment: 
      - "CASSANDRA_SEEDS=cassandra-1"
      - "CASSANDRA_CLUSTER_NAME=phd-cass"
      - "CASSANDRA_DC=se1"
      - "CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch"
    restart: unless-stopped
    networks: 
      - backend
    depends_on:
      cassandra-1:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2.3G
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "describe keyspaces" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 15s
    build:
      context: ./configs/cass
      
  cassandra-3:
    image: cassandra:phd-cass-3-11-9
    container_name: cassandra-3
    ports:
      - 9242:9042 # cqlsh
      - 7399:7199 # jmx
      - 7200:7000 # internode communication
      - 7201:7001 # tls internode
      - 7073:7070 # jmx
#      - 9303:9103 # jmx
    volumes:
      - "./data/cassandra-3:/var/lib/cassandra"
    environment: 
      - "CASSANDRA_SEEDS=cassandra-1"
      - "CASSANDRA_CLUSTER_NAME=phd-cass"
      - "CASSANDRA_DC=se1"
      - "CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch"
    restart: unless-stopped
    networks: 
      - backend
    depends_on:
      cassandra-1:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2.3G
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "describe keyspaces" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 15s
    build:
      context: ./configs/cass


  grafana:
    image: grafana/grafana 
    container_name: grafana
    links:
      - "prometheus"
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - ./data/grafana:/var/lib/grafana
    networks: 
      - backend
    environment: 
      - "GF_LOG_MODE=console"
      - "GF_LOG_CONSOLE_LEVEL=info"
      - "GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-piechart-panel"
      - "GF_DEFAULT_INSTANCE_NAME=grafana"
      - "GF_SERVER_DOMAIN=localhost"
      
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    links:
      - "cassandra-1"
      - "cassandra-2"
      - "cassandra-3"
      - "casstres-1"
    ports:
      - "9090:9090"
    volumes:
      - ./data/prometheus:/prometheus
      - ./configs/prom/prometheus.yml:/etc/prometheus/prometheus.yml
    networks: 
      - backend   
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
  
  casstres-1:
    container_name: casstres-1
    ports:
      - 8081:8080
    restart: unless-stopped
    networks: 
      - backend
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    healthcheck:
      test: "curl --fail --silent --request GET localhost:8080/actuator/health | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 40s
    build:
      context: ./configs/apps/cass
      
      
networks:
  backend: