global:
  scrape_interval: 15s
  evaluation_interval: 15s
  # scrape_timeout is set to the global default (10s).

  external_labels:
      monitor: 'phd'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'cassandra-1'
    static_configs:
      - targets: ['cassandra-1:7070']
        labels:
          service: 'cassandra-1'
          component: 'cassandra-1'
          environment: 'environment'
          data_center: 'se1'
          host: 'cassandra-1'
          
  - job_name: 'cassandra-2'
    static_configs:
      - targets: ['cassandra-2:7070']
        labels:
          service: 'cassandra-2'
          component: 'cassandra-2'
          environment: 'environment'
          data_center: 'se1'
          host: 'cassandra-2'
  
  - job_name: 'cassandra-3'
    static_configs:
      - targets: ['cassandra-3:7070']
        labels:
          service: 'cassandra-3'
          component: 'cassandra-3'
          environment: 'environment'
          data_center: 'se1'
          host: 'cassandra-3'
     
  - job_name: 'casstres-1'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['casstres-1:8080']
        labels:
          service: 'casstres-1'
          host: 'casstres-1'